### ISSUE TITLE
Release dates not always present, causes no games to display

### ISSUE THREAD

**Issue by cmgrayb** [hudsonbrendon/ha_epic_games#9]
Expected behavior: Games list updates on poll

Actual behavior: No games are listed, error in log

Log contents:
```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:682
integration: Sensor (documentation, issues)
First occurred: 10:49:42 AM (1 occurrences)
Last logged: 10:49:42 AM

epic_games: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 682, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1264, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/epic_games/sensor.py", line 185, in update
    runtime=game["viewableDate"].split("T")[0],
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by cmgrayb** [comment]
The issue has been resolved API side for the moment.  There is no remaining issue to test against.
